###############################################################################
#  Makefile.preamble
#  Copyright 1999, Apple Computer, Inc.
#
#  This file is for custom flags and settings that apply to the
#  kernel server.
###############################################################################

###############################################################################
# Flags to be passed to the compiler, linker, etc.
###############################################################################

# Any custom compiler flags you want to use
OTHER_CFLAGS = -I$(NEXT_ROOT)$(SYSTEM_LIBRARY_DIR)/Frameworks/System.framework/PrivateHeaders/machdep -Wno-format

# Any custom linker flags you want to use
# LDFLAGS +=
