###############################################################################
#  NeXT Makefile.preamble
###############################################################################

OTHER_CFLAGS = -g -Wall
OTHER_LDFLAGS =
OTHER_LIBS =
LIBS =
FRAMEWORKS =

MFILES = DPTSCSIDriver.m DPTSCSIDriverRoutines.m DPTSCSIDriverThread.m

HFILES = DPTSCSIDriver.h DPTSCSIDriverPrivate.h DPTSCSIDriverTypes.h

