#
# Makefile.preamble for PPCAwacs_reloc
#

# Compiler flags
OTHER_CFLAGS = -Wall -Wno-import -fno-common
OTHER_MFLAGS = -Wall -Wno-import -fno-common

# Linker flags for relocatable object
LDFLAGS = -r -nostdlib

# Include paths
INCLUDEPATHS = -I$(NEXT_ROOT)/System/Library/Frameworks/System.framework/PrivateHeaders \
               -I$(NEXT_ROOT)/System/Library/Frameworks/DriverKit.framework/Headers

# Architecture
ARCH_FLAGS = -arch ppc

# Optimization
OPTIMIZATION_CFLAG = -O2
