###############################################################################
#  NeXT Makefile.postamble Template
#  Copyright 1993, NeXT Computer, Inc.
#
#  This Makefile is used for configuring the standard app makefiles associated
#  with ProjectBuilder.
#
#  Use this template to set attributes for a project, sub-project, bundle, or
#  palette.  Each node in the project's tree of sub-projects and bundles
#  should have its own Makefile.preamble and Makefile.postamble.
#
###############################################################################

# top needs to be installed with kmem group permissions to read kernel memory
INSTALL_AS_GROUP = kmem
INSTALL_PERMISSIONS = 2755

# Signal include file location for sigdesc.h generation
SIGNAL = /usr/include/sys/signal.h

# Rule to generate sigdesc.h from signal definitions
# This file is needed by commands.c
sigdesc.h: sigconv.awk $(SIGNAL)
	$(AWK) -f sigconv.awk $(SIGNAL) >sigdesc.h

# Make sure sigdesc.h is built before compiling commands.c.
commands.o $(OFILE_DIR)/commands.o commands.ppc.o $(OFILE_DIR)/commands.ppc.o commands.i386.o $(OFILE_DIR)/commands.i386.o: sigdesc.h

# NeXT make VPATH-qualifies most ofiles on the link line but leaves bare
# commands.o. Lipo per-arch objects so a universal link can load i386.
ensure-commands-o: $(foreach A,$(RC_ARCHS),$(OFILE_DIR)/commands.$(A).o)
	$(RM) -f ./commands.o
	@thins="$(foreach A,$(RC_ARCHS),$(OFILE_DIR)/commands.$(A).o)"; \
	n=`echo $$thins | wc -w`; \
	if [ $$n -gt 1 ]; then \
	  lipo -create -output ./commands.o $$thins; \
	else \
	  $(CP) -p $$thins ./commands.o; \
	fi

# Additional clean targets
clean:
	-$(RM) -f sigdesc.h

# You can add more rules here if needed
