NAME = Terminal
PROJECTVERSION = 1.0
PROJECT_TYPE = Application
MFILES = CommandPanel.m DirtMonitor.m MiscController.m ProcessMonitorController.m StartupController.m TextAttributeController.m TitleBarController.m FieldView.m FieldPrint.m FontTrap.m FindPanel.m WindowController.m Preferences.m Terminal.m TerminalApp.m TerminalDO.m TerminalMain.m TerminalAgent.m TerminalDefaults.m ServiceCache.m ServiceManager.m ServiceProvider.m EmulationController.m ShellController.m Shell.m ShellExec.c ShellPolicy.c FlagMap.c ProcessInfo.c ProcessNames.c ProcessIdentity.c TerminalLaunch.c SavePanelMode.c TString.m Emulation.m vt52.m vt100.m MutableEvent.m Filer.m Filer.c Chunk.c TerminalScreen.c PathCompress.c WindowTitle.c WindowTitleRuntime.m WordBoundary.c WordSelection.c IntegerString.c PasteText.c DebugDPS.m FindCharacters.c PrintLine.c VT100Args.c VT100String.c VT100Parser.c VT100State.c
HFILES = CommandPanel.h DirtMonitor.h MiscController.h ProcessMonitorController.h StartupController.h TextAttributeController.h TitleBarController.h FieldView.h FieldPrint.h FontTrap.h FindPanel.h WindowController.h Preferences.h Terminal.h TerminalApp.h TerminalDefaults.h TerminalDO.h TerminalAgent.h ServiceManager.h ServiceManagerState.h ServiceProvider.h TerminalServices.h EmulationController.h ShellController.h Shell.h ShellExec.h ShellPolicy.h FlagMap.h ProcessInfo.h ProcessNames.h ProcessIdentity.h TerminalLaunch.h SavePanelMode.h TString.h Emulation.h MutableEvent.h FilerObjC.h Filer.h Chunk.h TerminalScreen.h PathCompress.h WindowTitle.h WindowTitleRuntime.h WordBoundary.h WordSelection.h IntegerString.h PasteText.h DebugDPS.h FindCharacters.h PrintLine.h VT100Args.h VT100String.h VT100Parser.h VT100State.h TerminalDOProtocol.h
OTHERSRCS = Makefile.preamble Makefile Makefile.postamble PB.project
MAKEFILEDIR = $(MAKEFILEPATH)/pb_makefiles
CODE_GEN_STYLE = DYNAMIC
MAKEFILE = app.make
NEXTSTEP_INSTALLDIR = /System/Administration
PDO_UNIX_INSTALLDIR = /System/Administration
LIBS =
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)
FRAMEWORKS = AppKit Foundation
NEXTSTEP_OBJCPLUS_COMPILER = /usr/bin/cc
WINDOWS_OBJCPLUS_COMPILER = $(DEVDIR)/gcc
PDO_UNIX_OBJCPLUS_COMPILER = $(NEXTDEV_BIN)/gcc
include $(MAKEFILEDIR)/platform.make
-include Makefile.preamble
include $(MAKEFILEDIR)/$(MAKEFILE)
-include Makefile.postamble
-include Makefile.dependencies
