###############################################################################
#  Makefile.preamble
#  Copyright 1999, Apple Computer, Inc.
#
#  This file is for custom flags and settings that apply to the
#  kernel server.
###############################################################################

###############################################################################
# Flags to be passed to the compiler, linker, etc.
###############################################################################

# Any custom compiler flags you want to use
# CFLAGS +=

# Any custom linker flags you want to use
# LDFLAGS +=

###############################################################################
# Where the headers go.
#
# The Makefile lists IOParallelPort.h and IOParallelPortKern.h as public
# headers, and the build refuses to install public headers without somewhere to
# put them ("Must set a public header directory to install public headers").
# Neither header ships on a Rhapsody system, so they go where the other kernel
# server drivers in this tree put theirs -- private, under bsd/dev.
###############################################################################

OTHER_PRIVATE_HEADERS := $(PUBLIC_HEADERS)
PUBLIC_HEADERS =

VERSION_DIR = Versions/B
SYSTEM_VERS_FRAMEWORK = $(SYSTEM_FRAMEWORK)/$(VERSION_DIR)

SYSTEM_VERS_HEADERS = $(SYSTEM_VERS_FRAMEWORK)/Headers
KERNEL_VERS_HEADERS = $(SYSTEM_VERS_FRAMEWORK)/PrivateHeaders

PUBLIC_HDR_INSTALLDIR  = $(SYSTEM_VERS_HEADERS)/bsd/dev
PRIVATE_HDR_INSTALLDIR = $(KERNEL_VERS_HEADERS)/bsd/dev
