##
# Makefile for apk-tools
##

# Project info
Project         = apk-tools
UserType        = Developer
ToolType        = Commands

# It's a GNU Source project
include $(MAKEFILEPATH)/CoreOS/ReleaseControl/GNUSource.make

Install_Target = install
