###############################################################################
#  Makefile.preamble
#  Copyright 1997, Apple Computer, Inc.
#
#  This makefile is included at the beginning of the common makefile.
###############################################################################

INCLUDED_ARCHS = i386

# Flags to pass to compiler
OTHER_CFLAGS = -DDRIVER_PRIVATE -Wno-format -I$(NEXT_ROOT)$(SYSTEM_LIBRARY_DIR)/Frameworks/System.framework/PrivateHeaders/machdep
OTHER_MFLAGS =
OTHER_LDFLAGS =

# Set these two macros to be empty to prevent any headers from being installed
PUBLIC_HEADERS =
PRIVATE_HEADERS =
