CC ?= cc
CFLAGS ?= -std=c89 -Wall -Wextra -Werror -pedantic
LINKROOT = ../IntelAC97.drvproj/IntelAC97.lksproj
TESTS = intel_ac97_test

.PHONY: all check clean

all: $(TESTS)

intel_ac97_test: intel_ac97_test.c \
        $(LINKROOT)/ICHAC97Controller.c \
        $(LINKROOT)/ICHAC97Controller.h \
        $(LINKROOT)/ac97.c \
        $(LINKROOT)/ac97var.h \
        $(LINKROOT)/ac97reg.h
	$(CC) $(CFLAGS) -I$(LINKROOT) -o $@ \
		intel_ac97_test.c \
		$(LINKROOT)/ICHAC97Controller.c \
		$(LINKROOT)/ac97.c

check: all
	./intel_ac97_test
	python3 driver_contract_test.py || python driver_contract_test.py

clean:
	rm -f $(TESTS) $(TESTS).exe *.o
