# Rhapsody port for RhapsodiOS, derived from makefile.nxt,v 4.13
#
#   Michael Seibel
#   Networks and Distributed Computing
#   Computing and Communications
#   University of Washington
#   Administration Builiding, AG-44
#   Seattle, Washington, 98195, USA
#   Internet: mikes@cac.washington.edu
#
#   Please address all bugs and comments to "pine-bugs@cac.washington.edu"
#
#
#   Pine and Pico are registered trademarks of the University of Washington.
#   No commercial use of these trademarks may be made without prior written
#   permission of the University of Washington.
#
#   Pine, Pico, and Pilot software and its included text are Copyright
#   1989-1998 by the University of Washington.
#
#   The full text of our legal notices is contained in the file called
#   CPYRIGHT, included with this distribution.
#

#
# Makefile for Rhapsody version of the stand-alone editor pico.
# CFLAGS for the target architectures arrive in EXTRACFLAGS and
# linker flags in EXTRALDFLAGS.
#

RM=          rm -f
LN=          ln -s
OPTIMIZE=    # -O
PROFILE=     # -pg
DEBUG=       # -g -DDEBUG

STDCFLAGS=	-Drhp -DJOB_CONTROL -DMOUSE
CFLAGS=         $(OPTIMIZE) $(PROFILE) $(DEBUG) $(EXTRACFLAGS) $(STDCFLAGS)

# termcap is part of System, which cc links by default
LIBS=		$(EXTRALDFLAGS)

OFILES=		attach.o basic.o bind.o browse.o buffer.o \
		composer.o display.o file.o fileio.o line.o pico_os.o \
		pico.o random.o region.o search.o \
		window.o word.o

HFILES=		headers.h estruct.h edef.h efunc.h pico.h os.h

#
# dependencies for the Rhapsody version of pico.  The objects are linked
# directly rather than through libpico.a: ranlib can't index an archive
# of fat (multi-architecture) objects.
#
all:		pico

pico:		main.o $(OFILES)
		$(CC) $(CFLAGS) main.o $(OFILES) $(LIBS) -o pico

clean:
		rm -f *.o *~ pico_os.c os.h pico osdep/os-rhp.c
		cd osdep; $(MAKE) clean; cd ..

os.h:		osdep/os-rhp.h
		$(RM) os.h
		$(LN) osdep/os-rhp.h os.h

pico_os.c:	osdep/os-rhp.c
		$(RM) pico_os.c
		$(LN) osdep/os-rhp.c pico_os.c

$(OFILES) main.o:	$(HFILES)
pico.o:				ebind.h

osdep/os-rhp.c:	osdep/header osdep/unix osdep/read.sel osdep/raw.ios \
		osdep/spell.unx osdep/term.cap \
		osdep/os-rhp.ic
		cd osdep; $(MAKE) includer os-rhp.c; cd ..
