##
# Makefile for ATIRage Display Driver
##

NAME = ATIRageDisplayDriver
BUNDLE_EXTENSION = config

OBJC_FILES = ATIRageDisplayDriver.m ATIRageDisplayDriverKernelServerInstance.m
HEADER_FILES = ATIRageDisplayDriver.h ATIRageDisplayDriverKernelServerInstance.h ATIRageRegs.h

OTHER_RESOURCES = Default.table
INSTALL_BIN_DIR = /System/Library/Drivers

MAKEFILEDIR = $(NEXT_ROOT)/NextDeveloper/Makefiles/app
MAKEFILE = bundle.make

include $(MAKEFILEDIR)/$(MAKEFILE)
