###############################################################################
#  NeXT Makefile.preamble
###############################################################################

OTHER_CFLAGS = -g -Wall
OTHER_LDFLAGS =
OTHER_LIBS =
LIBS =
FRAMEWORKS =

MFILES = AHAController.m AHAThread.m AHARoutines.m

HFILES = AHAController.h AHAControllerPrivate.h \
         AHAThread.h AHATypes.h AHAInline.h scsivar.h

