INCLUDED_ARCHS = i386
OTHER_CFLAGS = -I./PCMCIABus.lksproj

# SGS project and revision this driver shipped as, read out of the
# PCMCIABus_VERS_STRING in Apple's own PCMCIABus bundle. Drives the version
# stamp that makes the inner bundle link at all (see driver.make).
SGS_PROJECT_VERSION = drvPCMCIABus-15
