#!/bin/sh
# Like mv $1 $2, but if the files are the same, just delete $1.
# Status is 0 if $2 is changed, 1 otherwise.
# HFS-safe: rename-over-existing often fails with "Device busy".
hfs_mv() {
	if /bin/mv -f "$1" "$2" 2>/dev/null; then
		return 0
	fi
	rm -f "$2"
	cp -p "$1" "$2" && rm -f "$1"
}
if
test -r $2
then
if
cmp -s $1 $2
then
echo $2 is unchanged
rm -f $1
else
hfs_mv $1 $2
fi
else
hfs_mv $1 $2
fi
