#
# Makefile for drvPCFloppy
# PC Floppy Disk Controller Driver
#

NAME = Floppy

PROJECTVERSION = 5.10
LANGUAGE = English

LOCAL_RESOURCES =

GLOBAL_RESOURCES = Default.table

TOOLS = Floppy_reloc.tproj

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble

MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = bundle.make
SOURCEMODE = 444

BUNDLE_EXTENSION = config

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
