CC ?= cc
CFLAGS = -std=c89 -pedantic -Wall -Wextra -Werror
CORE = ../PPCTASAudio.drvproj/PPCTASAudio.lksproj/TASCore.c \
	../PPCTASAudio.drvproj/PPCTASAudio.lksproj/TAS3001C.c \
	../PPCTASAudio.drvproj/PPCTASAudio.lksproj/TAS3004.c \
	../PPCTASAudio.drvproj/PPCTASAudio.lksproj/PPCDBDMAAudio.c

.PHONY: all test clean
all: tas_audio_test

tas_audio_test: tas_audio_test.c tas_fixtures.c tas_fixtures.h $(CORE)
	$(CC) $(CFLAGS) -I../PPCTASAudio.drvproj/PPCTASAudio.lksproj \
	    tas_audio_test.c tas_fixtures.c $(CORE) -o $@

test: tas_audio_test
	./tas_audio_test

clean:
	rm -f tas_audio_test
