# Shared sources live in this aggregate; headers come from kernel-hdrs.
OTHER_CFLAGS = -Wno-precomp -I../common -I$(NEXT_ROOT)/System/Library/Frameworks/System.framework/Versions/B/Headers/bsd/ext2fs
INSTALL_AS_USER = root
INSTALL_AS_GROUP = wheel
INSTALL_PERMISSIONS = 0755
