HOST_CC ?= cc
HOST_CFLAGS ?= -std=c89 -pedantic -Wall -Wextra -Werror

TESTS = kauai_ata_test kiwi_ata_test

all: $(TESTS)

kauai_ata_test: kauai_ata_test.c ../KauaiATA.c ../KauaiATA.h
	$(HOST_CC) $(HOST_CFLAGS) -o $@ kauai_ata_test.c ../KauaiATA.c

kiwi_ata_test: kiwi_ata_test.c ../KiwiATA.c ../KiwiATA.h
	$(HOST_CC) $(HOST_CFLAGS) -o $@ kiwi_ata_test.c ../KiwiATA.c

test: $(TESTS)
	./kauai_ata_test
	./kiwi_ata_test

clean:
	rm -f $(TESTS)
