#!/bin/sh

##
# Run the Internet super-server.
##

. /etc/rc.common

ConsoleMessage "Starting TCP/IP services"

inetd

##
# Start up network boot cofiguration services.
##

if [ "${CONFIGSERVER:=-NO-}" = "-YES-" ]; then
    ConsoleMessage "Starting host configuration services"

    if [ "${NETBOOTSERVER:=-NO-}" = "-YES-" ]; then
	bootpd -m
    else
	bootpd
    fi

    bootparamd
fi

##
# Start up network client management services.
##

if [ "${MANAGEMENTSERVER:=-NO-}" = "-YES-" ]; then
    ConsoleMessage "Starting netboot client management server"

    MacintoshManagementServer &
fi

##
# Start up secure login server
##

if [ "${SSHSERVER:=-NO-}" = "-YES-" ]; then
    ConsoleMessage "Starting Secure Login Server"

    if [ ! -f /etc/ssh_host_key ]; then
        echo "Generating ssh host RSA key..."
        ssh-keygen -f /etc/ssh_host_key -N "" -C "$(hostname)"
    fi
    if [ ! -f /etc/ssh_host_dsa_key ]; then
        echo "Generating ssh host DSA key..."
        ssh-keygen -d -f /etc/ssh_host_dsa_key -N "" -C "$(hostname)"
    fi

    /usr/sbin/sshd &
fi
