###############################################################################
#  NeXT Makefile.postamble
###############################################################################

# driver.make movehelp always mv's English.lproj/DriverHelp; this stub has none.
movehelp:
	@true

