LOCALMAKEFILEDIR = /LocalDeveloper/Makefiles/driverkit
LOCALMAKEFILE = Makefile.local_preamble
-include $(LOCALMAKEFILEDIR)/$(LOCALMAKEFILE)
INSTALL_EXAMPLE = YES

BUNDLE_EXTENSION = config

bundle all::
	rm -rf $(PRODUCT_ROOT)/English.lproj/Help
