profile=gcc-darwin-ppc-macho
build_cc=/usr/bin/cc
target_cc=/usr/bin/cc
target_arch=ppc
target_ar=/usr/bin/ar
target_ranlib=/usr/bin/ranlib
make=/usr/bin/make
shell=/bin/sh
tar=/usr/bin/gnutar
archive_create=/bin/pax
archive_create_flags=-w -x ustar
gzip=/usr/bin/gzip
rsync=/usr/bin/rsync
path=/build/tools/bin:/usr/bin:/bin:/usr/sbin:/sbin
arch_flags=-arch ppc
cpp_flags=-nostdinc -F@SYSROOT@/System/Library/Frameworks -I@SYSROOT@/System/Library/Frameworks/System.framework/Headers -I@SYSROOT@/System/Library/Frameworks/System.framework/PrivateHeaders
ld_flags=-Wl,-syslibroot,@SYSROOT@
ln=/bin/ln
