###############################################################################
#  NeXT Makefile.preamble
###############################################################################

OTHER_CFLAGS = -g -Wall
OTHER_LDFLAGS =
OTHER_LIBS =
LIBS =
FRAMEWORKS =

MFILES = EATAController.m EATAControllerThread.m

HFILES = EATAController.h EATAControllerPrivate.h EATAControllerTypes.h

CFILES = EATAControllerRoutines.c

