NAME = CirrusLogicGD5434
BUNDLE_EXTENSION = config
DRIVERKIT_DEVICE = YES

INSTALLDIR = $(SYSTEM_LIBRARY_DIR)/Devices

M_FILES = CirrusLogicGD5434DisplayDriver.m
PUBLIC_HEADERS = CirrusLogicGD5434DisplayDriver.h

OTHERSRCS = Makefile Default.table

LIBS = -ldriver
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)

FRAMEWORKS = -framework DriverKit -framework IOKit

include ../Makedefs
