##
# Makefile for BusMouse driver
##

NAME = BusMouse
BUNDLE_EXTENSION = config

OBJC_FILES = BusMouseDriver.m
HEADER_FILES = BusMouseDriver.h BusMouseRegs.h BusMouseTypes.h

OTHER_RESOURCES = BusMouse.table
INSTALL_BIN_DIR = /System/Library/Drivers

MAKEFILEDIR = $(NEXT_ROOT)/NextDeveloper/Makefiles/app
MAKEFILE = bundle.make

include $(MAKEFILEDIR)/$(MAKEFILE)
