##
# Makefile for RCS
##

# Project info
Project               = rcs
Extra_Configure_Flags = --with-diffutils
UserType              = Developer
ToolType              = Commands

# It's a GNU Source project
include $(MAKEFILEPATH)/CoreOS/ReleaseControl/GNUSource.make
