###############################################################################
#  NeXT Makefile.preamble
###############################################################################

CLASSES = EtherLinkXL.m EtherLinkXLKDB.m EtherLinkXLMII.m EtherLinkXLPrivate.m
HFILES = EtherLinkXL.h
