###############################################################################
#  NeXT Makefile.postamble
#  Copyright 1996, NeXT Software, Inc.
#
#  This Makefile is used for configuring the standard app makefiles associated
#  with ProjectBuilder.
#
###############################################################################
