###############################################################################
#  NeXT Makefile.preamble
###############################################################################

OTHER_CFLAGS = -g -Wall
OTHER_LDFLAGS =
OTHER_LIBS =
LIBS =
FRAMEWORKS =

MFILES = BusLogicController.m BusLogicThread.m BusLogicRoutines.m

HFILES = BusLogicController.h BusLogicControllerPrivate.h \
         BusLogicThread.h BusLogicTypes.h BusLogicInline.h scsivar.h

