NAME = SoundBlaster16_reloc

CFILES = SoundBlaster16.m

HFILES = SoundBlaster16.h SoundBlaster16Registers.h SoundBlaster16Inline.h

MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = tool.make

LIBS = -lDriver

OTHER_CFLAGS = -DDRIVER_PRIVATE

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
