/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /CVSRoot/CoreOS/Development/flex/flex/skel.c,v 1.1.1.1 1997/08/14 18:29:21 wsanchez Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + yy_more_offset >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[yy_more_offset], yytext_ptr, yyleng + 1 ); \
	yyleng += yy_more_offset; \
	yy_prev_more_offset = yy_more_offset; \
	yy_more_offset = 0; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
static yyconst short int yy_acclist[436] =
    {   0,
       68,   67,   63,   67,   64,   67,   67,   67,   67,   63,
       67,   64,   67,   67,   67,   55,   67,   61,   63,   67,
       62,   64,   67,   61,   67,   67,16416,   36,   67,   60,
       67,   55,   67,   55,   67,   55,   67,   54,   67,   33,
       35,   55,   67,   45,   67,   60,   67,   52,   67,   60,
       67,   55,   67,   55,   67,   55,   67,   61,   63,   67,
       62,   64,   67,   61,   67,   55,   67,   44,   67,   44,
       63,   67,   43,   64,   67,   37,   67,   38,   67,   44,
       67,   44,   67,   67,   44,   67,   44,   63,   67,   43,
       64,   67,   44,   67,   44,   67,   49,   67,   46,   63,

       67,   46,   64,   67,   46,   67,   49,   67,   49,   67,
       47,   67,   48,   67,   47,   67,   46,   63,   67,   46,
       64,   67,   46,   67,   47,   67,   31,   67,   30,   63,
       67,   30,   64,   67,   30,   67,   11,   67,   12,   67,
       13,   67,   13,   67,   67,   27,   67,   26,   67,   29,
       67,   29,   67,   29,   67,   29,   67,   29,   67,   29,
       67,   29,   67,   29,   67,   29,   67,   29,   67,   29,
       67,   29,   67,   30,   63,   67,   30,   64,   67,   30,
       67,   29,   67,   29,   67,   67,   63,   66,   65,   63,
       55,   61,   63,   61,   62,16416, 8224,   60,   56,   66,

       55,   33,   35,   55,   35,   55,   54,   54,   65,   55,
       35,   55,   33,   35,   55,   55,   50,   51,   60,16441,
       55,   55,   55,   61,   63,   61,   62,   55,   44,   44,
       63,   44,   66,   44,   65,   42,   40,   39,   42,   41,
       42,   44,   44,   63,   44,   44,   44,   49,   46,   63,
       46,   49,   66,   49,   65,   47,   46,   63,   46,   47,
       31,   30,   63,   30,   10,   66,    9,   65,   27,   26,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   30,   63,   30,   29,   29,   58,
       59,   55,   34,   55,   35,   55,   55,   35,   55, 8249,

       55,   55,   55,   55,   39,   44,   44,   44,   47,   28,
       29,   29,   29,   29,   29,   29,   17,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   59,   55,   35,   55,
       55,   55,   55,   53,   55,   55,   39,   44,   44,   44,
       29,   29,   16,   29,   29,   29,   29,   19,   29,   29,
       29,   29,   29,   29,   29,   29,    8,   55,   35,   55,
        5,    8,   55,   55,    8,   44,   44,   44,   29,   29,
       29,    8,   29,   21,   29,   29,   18,   29,   29,   29,
       29,   29,    6,    8,   29,   55,   44,   44,   29,   29,
       22,   29,   29,   14,   29,   29,   29,   29,   55,   44,

       44,   29,   15,   29,   29,   29,   29,   29,    4,    1,
        4,   55,   44,    3,    4,    7,   44,   29,   29,   20,
       29,   29,    2,    4,   29,    4,   44,   29,   24,   29,
       29,   25,   29,   23,   29
    } ;

static yyconst short int yy_accept[309] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    3,    5,    7,    8,    9,   10,
       12,   14,   15,   16,   18,   21,   24,   26,   28,   30,
       32,   34,   36,   38,   40,   44,   46,   48,   50,   52,
       54,   56,   58,   61,   64,   66,   68,   70,   73,   76,
       78,   80,   82,   84,   85,   87,   90,   93,   95,   97,
       99,  102,  105,  107,  109,  111,  113,  115,  117,  120,
      123,  125,  127,  129,  132,  135,  137,  139,  141,  143,
      145,  146,  148,  150,  152,  154,  156,  158,  160,  162,
      164,  166,  168,  170,  172,  174,  177,  180,  182,  184,

      186,  187,  188,  189,  190,  190,  191,  191,  191,  191,
      192,  194,  195,  196,  197,  198,  199,  201,  202,  205,
      207,  208,  210,  211,  213,  216,  217,  218,  220,  221,
      222,  223,  224,  226,  227,  228,  229,  230,  232,  234,
      236,  237,  238,  240,  242,  243,  245,  246,  247,  248,
      249,  251,  252,  254,  256,  257,  259,  260,  261,  262,
      264,  265,  267,  269,  270,  270,  271,  272,  273,  274,
      275,  276,  277,  278,  279,  280,  281,  282,  283,  284,
      285,  287,  288,  289,  290,  290,  290,  292,  292,  292,
      293,  295,  297,  298,  300,  301,  302,  303,  304,  305,

      306,  307,  308,  309,  310,  311,  312,  313,  314,  315,
      316,  317,  319,  320,  321,  322,  323,  324,  325,  326,
      327,  328,  328,  328,  329,  331,  332,  333,  334,  336,
      337,  338,  339,  340,  341,  342,  343,  345,  346,  347,
      348,  350,  351,  352,  353,  354,  355,  356,  357,  358,
      358,  359,  361,  364,  365,  367,  368,  369,  370,  371,
      372,  374,  376,  377,  379,  380,  381,  382,  383,  386,
      386,  387,  388,  389,  390,  391,  393,  394,  396,  397,
      398,  399,  399,  400,  401,  402,  403,  405,  406,  407,
      408,  409,  410,  413,  414,  418,  419,  420,  422,  423,

      426,  428,  429,  431,  432,  434,  436,  436
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    5,    1,    6,    1,    1,    7,
        8,    9,   10,   11,   10,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   16,   16,   11,   11,   17,
        1,   18,    1,    1,   19,   19,   20,   21,   22,   19,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   24,
       23,   23,   25,   23,   23,   23,   23,   26,   23,   23,
       27,   28,   29,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   40,   23,   41,   42,   43,
       44,   45,   23,   46,   47,   48,   49,   23,   23,   50,
       23,   23,   51,   11,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    2,    3,    2,    1,    4,    5,    6,    7,    1,
        7,    1,    8,    9,    9,    9,    4,   10,    9,    9,
        9,    9,   11,   11,   11,   11,    8,   12,    8,   11,
        9,    9,    9,    9,    9,    9,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
        4
    } ;

static yyconst short int yy_base[325] =
    {   0,
        0,    2,   37,   87,  120,  154,  188,  223,  259,   90,
       99,  309,  752,  753,  749,  753,  737,  740,  705,   96,
      101,  107,  712,    0,    6,  743,   10,  742,  753,   88,
      731,    4,    7,  734,  131,  725,   89,  753,  124,  698,
      709,  693,  116,  135,  171,  703,    0,  735,  753,  753,
      753,  723,  726,  156,  691,  177,  183,  196,  698,    0,
       22,   25,   28,  719,  722,    0,  753,  687,  212,  312,
      317,  694,    0,  111,  174,  191,  753,  753,  715,  753,
      718,  309,  219,    0,  702,  681,  686,  679,  679,  680,
      677,  675,  669,  106,  117,  324,  327,  330,   96,  674,

        5,  714,  753,  753,  681,  335,  338,  679,  677,    0,
      147,  227,  709,  708,  753,  337,  753,  233,  338,  352,
        0,    0,  370,  362,  380,  389,  753,  380,  383,  676,
      668,  659,  410,  414,  417,  671,    0,  704,    0,    0,
      753,  753,  198,  753,  671,  420,  423,  669,  667,    0,
      248,  345,    0,    0,    0,  426,  429,  666,    0,  432,
      435,  753,  753,  426,    0,  431,    0,  676,  656,  668,
      649,  663,  652,  647,  651,  651,  648,  660,  643,  654,
      462,  465,  652,  640,  354,  643,  753,  625,  630,  460,
      472,  471,  464,  474,  753,  623,  620,  631,  612,  348,

      603,  610,  606,  605,    0,  623,  601,  594,  607,  590,
      603,    0,  591,  580,  562,  559,  566,  552,  556,  549,
      753,  546,  549,  489,  493,  500,  541,  551,    0,  541,
      753,  536,  543,  538,  536,  530,    0,  522,  514,  512,
        0,  511,  510,  518,  464,  456,  455,  450,  753,  460,
      497,  503,    0,  459,    0,  449,  456,  429,  440,  427,
        0,    0,  415,    0,  426,  415,  424,  420,    0,  408,
      407,  415,  404,  395,  366,    0,  368,    0,  371,  353,
      345,  342,  339,  325,  310,  282,    0,  210,  206,  193,
      171,  753,    0,  149,    0,  133,  135,    0,  135,    0,

        0,  117,    0,   47,    0,    0,  753,  519,  531,  543,
      555,  566,  578,  590,  602,  613,  625,   24,  637,  641,
      652,  664,    8,  675
    } ;

static yyconst short int yy_def[325] =
    {   0,
      308,  308,  307,    3,  309,  309,  310,  310,  307,    9,
      308,  308,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  311,  307,  307,  307,  312,  307,  307,
      311,  311,  311,  313,  311,  307,  307,  307,  314,  311,
      311,  311,  307,  307,  307,  311,  315,  315,  307,  307,
      307,  315,  315,  316,  315,  315,  307,  315,  315,  317,
      307,  307,  307,  317,  317,  318,  307,  318,  307,  307,
      307,  318,  319,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  307,  307,  307,  320,  320,

      321,  307,  307,  307,  307,  307,  307,  307,  307,  311,
      307,  307,  307,  312,  307,  307,  307,  311,  311,  311,
      313,  313,  322,  311,  311,  311,  307,  307,  314,  311,
      311,  311,  307,  307,  307,  311,  315,  315,  315,  315,
      307,  307,  307,  307,  315,  315,  315,  315,  315,  317,
      307,  307,  317,  317,  318,  307,  307,  318,  319,  307,
      307,  307,  307,  307,  323,  307,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      307,  307,  320,  320,  321,  324,  307,  307,  307,  311,
      322,  311,  311,  311,  307,  311,  311,  311,  311,  307,

      315,  315,  315,  318,  323,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      307,  307,  307,  311,  311,  311,  311,  311,  311,  311,
      307,  315,  315,  315,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  307,  307,
      311,  311,  311,  311,  315,  315,  315,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  307,
      311,  315,  315,  320,  320,  320,  320,  320,  320,  320,
      320,  307,  311,  315,  315,  320,  320,  320,  320,  320,
      320,  307,  311,  315,  315,  320,  320,  320,  320,  320,

      315,  320,  320,  320,  320,  320,    0,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307
    } ;

static yyconst short int yy_nxt[805] =
    {   0,
      307,   15,   16,   20,   21,   22,  186,  111,   17,  112,
       17,  112,   18,  112,   18,  118,  205,  119,  119,  119,
      120,  120,  120,  151,  152,  152,  152,  152,  152,  152,
      152,  152,  155,  187,   19,   23,   19,   24,   25,   26,
       27,   24,   28,   29,   30,   31,   32,   24,   33,   34,
       35,   35,   35,   36,   37,   24,   24,   24,   24,   24,
       24,   24,   24,   38,   39,   38,   24,   24,   24,   24,
       24,   40,   41,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   42,   24,   24,   38,   43,   44,
       45,   96,   97,   98,  306,  116,  116,  106,  107,  107,

       15,   16,  107,  107,  107,  116,  128,   17,  107,  107,
      107,   18,  160,  161,  161,  116,  116,  133,  107,  134,
       46,   48,   49,   99,  100,  101,   50,   51,   52,  108,
      183,  116,   53,   19,  108,  123,  107,  135,  107,  171,
      108,  116,  124,  177,  125,  125,  125,   54,  111,  108,
      112,  116,  126,  178,   55,   56,   57,   58,  142,  179,
       50,   51,   52,  180,  305,  126,   53,  304,  108,  143,
      143,  303,  134,  107,  134,  161,  161,  161,  146,  107,
      147,   54,  302,  144,  107,  107,  107,   59,   55,   61,
       62,   63,  161,  161,  161,  301,   64,  147,  107,  147,

       65,   66,   66,   66,  108,   67,   66,   66,   66,   66,
      148,  200,  200,  156,  157,  157,  108,  300,   66,   66,
       66,   66,   68,   66,   69,   70,   71,  299,  112,  148,
      112,   64,  166,  166,  166,   65,   66,   66,   66,  298,
       67,   66,   66,   66,   66,  108,  120,  120,  120,  151,
      152,  152,  297,   66,   66,   66,   72,   68,   66,   73,
       74,   75,   76,   73,   73,   77,   78,   79,   73,   80,
       73,   81,   82,   83,   83,   73,   73,   84,   84,   85,
       84,   84,   84,   84,   84,   80,   73,   80,   84,   84,
       86,   87,   88,   89,   90,   84,   84,   91,   84,   92,

       84,   93,   84,   84,   84,   94,   84,   95,   84,   73,
       20,   21,   22,  157,  157,  157,  296,   17,  157,  157,
      157,   18,  164,  164,  164,  181,  182,  182,  182,  182,
      182,  182,  182,  182,  165,  101,  106,  107,  107,  107,
      107,  107,   23,   19,  116,  108,  152,  152,  152,  124,
      108,  119,  119,  119,  116,  186,  295,  108,  165,  126,
      108,  231,  231,  108,  116,  120,  120,  120,  108,  294,
      110,  108,  126,  190,  110,  192,  192,  192,  110,  110,
      110,  110,  187,  126,  123,  293,  190,  116,  292,  291,
      307,  124,  290,  125,  125,  125,  126,  116,  193,  110,

      307,  126,  194,  194,  194,  289,  288,  116,  287,  195,
      307,  133,  107,  134,  126,  134,  107,  134,  107,  135,
      107,  146,  107,  147,  147,  107,  147,  156,  157,  157,
      157,  157,  157,  160,  161,  161,  161,  161,  161,  164,
      164,  164,  286,  108,  166,  166,  166,  108,  285,  284,
      108,  283,  282,  148,  281,  280,  148,  279,  278,  108,
      277,  276,  108,  181,  182,  182,  182,  182,  182,  224,
      275,  274,  110,  225,  225,  225,  110,  194,  194,  194,
      110,  110,  110,  110,  192,  192,  192,  194,  194,  194,
      273,  272,  226,  271,  270,  108,  269,  268,  108,  267,

      266,  110,  225,  225,  225,  226,  225,  225,  225,  251,
      252,  252,  252,  252,  252,  252,  252,  252,  252,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,  110,  265,  264,  263,  262,
      261,  110,  260,  110,  259,  110,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  121,  258,
      257,  256,  255,  254,  121,  229,  121,  253,  121,  121,
      129,  250,  249,  248,  247,  129,  129,  246,  129,  129,

      129,  129,  137,  137,  245,  137,  244,  243,  137,  137,
      137,  137,  137,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  150,  242,  241,  150,  150,
      150,  150,  150,  240,  239,  150,  150,  159,  238,  237,
      159,  236,  235,  223,  234,  233,  159,  232,  159,  167,
      230,  167,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  191,  229,  228,  227,  223,  222,
      191,  221,  191,  220,  191,  186,  186,  186,  186,  186,
      186,  186,  186,  186,  186,  186,  186,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,

      206,  204,  203,  202,  201,  138,  199,  198,  197,  196,
      115,  113,  189,  109,  188,  102,  184,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  163,  162,  158,  105,
      154,  153,  149,  145,  140,  139,  138,  136,  132,  131,
      130,  127,  122,  117,  115,  113,  109,  105,  104,  103,
      102,  307,   13,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307
    } ;

static yyconst short int yy_chk[805] =
    {   0,
        0,    1,    1,    2,    2,    2,  101,   25,    1,   25,
        2,   27,    1,   27,    2,   32,  323,   32,   32,   32,
       33,   33,   33,   61,   61,   61,   62,   62,   62,   63,
       63,   63,  318,  101,    1,    2,    2,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    4,    4,
        4,   10,   10,   10,  304,   30,   37,   20,   20,   20,

       11,   11,   21,   21,   21,   30,   37,   11,   22,   22,
       22,   11,   74,   74,   74,   30,   37,   43,   43,   43,
        4,    5,    5,   10,   10,   11,    5,    5,    5,   20,
       99,   39,    5,   11,   21,   35,   44,   44,   44,   99,
       22,   39,   35,   94,   35,   35,   35,    5,  111,   43,
      111,   39,   35,   94,    5,    6,    6,    6,   54,   95,
        6,    6,    6,   95,  302,   35,    6,  299,   44,   54,
       54,  297,   45,   45,   45,   75,   75,   75,   56,   56,
       56,    6,  296,   54,   57,   57,   57,    6,    6,    7,
        7,    7,   76,   76,   76,  294,    7,   58,   58,   58,

        7,    7,    7,    7,   45,    7,    7,    7,    7,    7,
       56,  143,  143,   69,   69,   69,   57,  291,    7,    7,
        7,    7,    7,    7,    8,    8,    8,  290,  112,   58,
      112,    8,   83,   83,   83,    8,    8,    8,    8,  289,
        8,    8,    8,    8,    8,   69,  118,  118,  118,  151,
      151,  151,  288,    8,    8,    8,    8,    8,    8,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       12,   12,   12,   70,   70,   70,  286,   12,   71,   71,
       71,   12,   82,   82,   82,   96,   96,   96,   97,   97,
       97,   98,   98,   98,   82,   12,  106,  106,  106,  107,
      107,  107,   12,   12,  116,   70,  152,  152,  152,  119,
       71,  119,  119,  119,  116,  185,  285,   96,   82,  119,
       97,  200,  200,   98,  116,  120,  120,  120,  106,  284,
      123,  107,  119,  120,  123,  124,  124,  124,  123,  123,
      123,  123,  185,  124,  125,  283,  120,  128,  282,  281,
      129,  125,  280,  125,  125,  125,  124,  128,  126,  123,

      129,  125,  126,  126,  126,  279,  277,  128,  275,  129,
      129,  133,  133,  133,  125,  134,  134,  134,  135,  135,
      135,  146,  146,  146,  147,  147,  147,  156,  156,  156,
      157,  157,  157,  160,  160,  160,  161,  161,  161,  164,
      164,  164,  274,  133,  166,  166,  166,  134,  273,  272,
      135,  271,  270,  146,  268,  267,  147,  266,  265,  156,
      263,  260,  157,  181,  181,  181,  182,  182,  182,  190,
      259,  258,  191,  190,  190,  190,  191,  193,  193,  193,
      191,  191,  191,  191,  192,  192,  192,  194,  194,  194,
      257,  256,  192,  254,  250,  181,  248,  247,  182,  246,

      245,  191,  224,  224,  224,  192,  225,  225,  225,  226,
      251,  251,  251,  226,  226,  226,  252,  252,  252,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  309,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  309,  310,  310,  310,  310,  310,  310,  310,
      310,  310,  310,  310,  310,  311,  244,  243,  242,  240,
      239,  311,  238,  311,  236,  311,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  313,  235,
      234,  233,  232,  230,  313,  228,  313,  227,  313,  313,
      314,  223,  222,  220,  219,  314,  314,  218,  314,  314,

      314,  314,  315,  315,  217,  315,  216,  215,  315,  315,
      315,  315,  315,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  317,  214,  213,  317,  317,
      317,  317,  317,  211,  210,  317,  317,  319,  209,  208,
      319,  207,  206,  204,  203,  202,  319,  201,  319,  320,
      199,  320,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  322,  198,  197,  196,  189,  188,
      322,  186,  322,  184,  322,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  183,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,

      168,  158,  149,  148,  145,  138,  136,  132,  131,  130,
      114,  113,  109,  108,  105,  102,  100,   93,   92,   91,
       90,   89,   88,   87,   86,   85,   81,   79,   72,   68,
       65,   64,   59,   55,   53,   52,   48,   46,   42,   41,
       40,   36,   34,   31,   28,   26,   23,   19,   18,   17,
       15,   13,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() (yy_more_offset = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	yy_more_offset = yy_prev_more_offset; \
	yyleng -= yy_more_offset; \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
/*
  lexer.l

Copyright (c) 1988 Adobe Systems Incorporated.
All rights reserved.

PostScript is a registered trademark of Adobe Systems Incorporated.
Display PostScript is a trademark of Adobe Systems Incorporated.

Original version: Andrew Shore 
Edit History:
Andrew Shore: Wed Aug 17 10:59:46 1988
Ivor Durham: Tue May 24 19:53:49 1988
William Bilodeau: Fri Jun 29 17:38:35 PDT 1990
Richard Cohn: Fri Oct 21 15:17:07 1988
End Edit History.
*/

#ifdef os_mpw
#include <cursorctl.h>
#endif
#include <ctype.h>
#include "pswpriv.h"
#include "y.tab.h"


extern int outlineno;		/* output line number */

extern int maxstring;		/* max PS string length to scan (-s) */
extern char *string_temp;	/* buffer of that size for scanning strings */
extern char *psw_malloc();
extern void stringerr();	/* report string overflow */
extern char *ifile;		/* input file name for error messages */

static int parens = 0;		/* current paren balancing */
static char *sbody;		/* cur pointer into string_temp */
static int curleng = 0;		/* current scanned string length */
static int strlineno;		/* start line of current string */

static int nonComment = true;	/* are we outside C comments? */
static int newLine = true;	/* are we starting a new line? */
static int hexstringerrs = 0;	/* found an error in this hex string */

int errorCount = 0;		/* number of non-fatal errors */


/* for debugging */
#ifdef PSWDEBUG
int lexdebug = 1;		/* debug flag */
#define DEBUGP(x) {if (lexdebug) { fprintf x ; };}
#else
#define DEBUGP(x)
#endif
#ifdef LEXDEBUG
#ifdef os_mpw
void allprint(c)
	char c;
{
	if (c >= ' ') putc((c), yyout);
	else if (c == 10) fputs("\\n", yyout);
	else fprintf(yyout, "\\%x", c);
}
void sprint(s)
	char *s;
{
	char *p = s;
	while(*p) allprint(*p++);
}
#endif
#endif


#ifdef os_mpw
#undef input
#undef unput
#define input() (((yytchar=yysptr>yysbuf?U(*--yysptr):getc(yyin))==13?(yylineno++,yytchar=10):yytchar)==EOF?0:yytchar)
#define unput(c) {yytchar= (c);if(yytchar==10){yylineno--;yytchar=13;}*yysptr++=yytchar;}
#endif

#undef YYLMAX
#define YYLMAX 16384
#define PS 1
#define STR 2
#define HEX 3
#define DEF 4
#define SUB 5

#line 821 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 98 "lexer.l"


#line 978 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 308 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 753 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 100 "lexer.l"
{	/* inside a wrap - just a PS token */
	if (nonComment) {
	    newLine = false;
	    yylval.object = psw_malloc(strlen(yytext) + 1);
	    strcpy(yylval.object, yytext);
	    DEBUGP((stderr,"PSNAME ->%s\n",yytext));
	    return PSNAME;
	}
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 110 "lexer.l"
{ 	/* treat as a C name inside the def part */
	if (nonComment) {
	    yylval.object = psw_malloc(strlen(yytext) + 1);
	    strcpy(yylval.object, yytext);
	    DEBUGP((stderr,"CNAME ->%s\n",yytext));
	    return CNAME;
	}
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 119 "lexer.l"
{	/* part of string text */
	register int i = yyleng;
	register char *c = yytext;

	if (yyleng + curleng >= maxstring) {
		stringerr(1);
		BEGIN PS;
		*sbody = '\0';
		return PSSTRING;
	}
	curleng += yyleng;
	for (; i > 0; --i) *sbody++ = *c++;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 133 "lexer.l"
{ 		/* start of a wrap definition */
	if (nonComment) {
	    BEGIN DEF;
	    DEBUGP((stderr,"DEFINEPS\n"));
	    return DEFINEPS;
	} else ECHO;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 141 "lexer.l"
{		/* end of a wrap */
	if (nonComment){
	    if (newLine) {
	        newLine = false;
	    	DEBUGP((stderr,"ENDPS\n"));
	    	BEGIN 0;
	    	return ENDPS;
	    } else {
	    	DEBUGP((stderr,"PSNAME %s\n",yytext));
	    	yylval.object = psw_malloc(strlen(yytext) + 1);
	    	strcpy(yylval.object, yytext);
	    	return PSNAME;
	    }
	}	    
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 157 "lexer.l"
{ 	/* treat as a C name inside the def part? */
	if (nonComment) {
	    yylval.object = psw_malloc(strlen(yytext) + 1);
	    strcpy(yylval.object, yytext);
	    DEBUGP((stderr,"CNAME ->%s\n",yytext));
	    return CNAME;
	}
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 166 "lexer.l"
{	/* part of string text */
	register int i = yyleng;
	register char *c = yytext;

	if (yyleng + curleng >= maxstring) {
		stringerr(1);
		BEGIN PS;
		*sbody = '\0';
		return PSSTRING;
	}
	curleng += yyleng;
	for (; i > 0; --i) *sbody++ = *c++;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 180 "lexer.l"
{ 		/* BOGUS end of a wrap */
	if (nonComment) {
	    ErrIntro(yylineno);
	    fprintf(stderr,"endps without matching defineps\n");
	} else ECHO;
}
	YY_BREAK

    	/* real definition stuff */

case 9:
YY_RULE_SETUP
#line 191 "lexer.l"
{		/* C comments on */
	nonComment = false;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 195 "lexer.l"
{		/* C comments off */
	nonComment = true;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 199 "lexer.l"
{	/* formals start */
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->(\n"));
	    return '(';
	}
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 206 "lexer.l"
{	/* formals end */
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->)\n"));
	    BEGIN PS;
	    return ')';
	}
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 214 "lexer.l"
{	/* special single chars */
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->%c\n",yytext[0]));
	    return (yytext[0]);
	}
}
	YY_BREAK

	/* formals type names */

case 14:
YY_RULE_SETUP
#line 225 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->static\n"));
	    return STATIC;
	}
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 232 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->boolean\n"));
	    return BOOLEAN;
	}
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 239 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->char\n"));
	    return CHAR;
	}
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 246 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->int\n"));
	    return INT;
	}
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 253 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->short\n"));
	    return SHORT;
	}
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 260 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->long\n"));
	    return LONG;
	}
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 267 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->unsigned\n"));
	    return UNSIGNED;
	}
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 274 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->float\n"));
	    return FLOAT;
	}
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 281 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->double\n"));
	    return DOUBLE;
	}
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 288 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->userobject\n"));
	    return USEROBJECT;
	}
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 295 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->numstring\n"));
	    return NUMSTRING;
	}
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 302 "lexer.l"
{
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->DPScontext\n"));
	    return PSCONTEXT;
	}
}
	YY_BREAK

	/* C format numbers in formals part */

case 26:
YY_RULE_SETUP
#line 313 "lexer.l"
{ 		/* base 10 number */
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->CINTEGER %s\n",yytext));
	    yylval.intobj = atoi(yytext);
	    return CINTEGER;
	}
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 321 "lexer.l"
{		/* octal number (and zero) */
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->CINTEGER %s\n",yytext));
	    sscanf(yytext,"%lo",&yylval.intobj);
	    return CINTEGER;
	}
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 329 "lexer.l"
{		/* hex number */
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->CINTEGER %s\n",yytext));
	    sscanf(yytext,"0x%lx",&yylval.intobj);
	    return CINTEGER;
	}
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 337 "lexer.l"
{	/* C identifier */
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->CNAME %s\n",yytext));
	    yylval.object = psw_malloc(strlen(yytext) + 1);
	    strcpy(yylval.object, yytext);
	    return CNAME;
	}
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 346 "lexer.l"
{
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 349 "lexer.l"
{	/* all else - ERROR */
	if (nonComment) {
	    DEBUGP((stderr,"DEF ->JUNK %s\n",yytext));
	    ErrIntro(yylineno);
	    fprintf(stderr,"invalid characters '%s' in definition\n",
	    	yytext);
	}
}
	YY_BREAK

	/* body part - PostScript code */

case 32:
YY_RULE_SETUP
#line 363 "lexer.l"
{			/* a PS comment, ignore */
	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"comment %s\n",yytext));
	    /* yylval = yytext; return PSCOMMENT; */
	}
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 371 "lexer.l"
{		/* a decimal integer */
	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"PSINTEGER ->%s\n",yytext));
	    yylval.intobj = atoi(yytext);
	    return PSINTEGER;
	}
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 380 "lexer.l"
{	/* a radix number */
#define MAX_ULONG ((unsigned long) -1)
	int base = 0;
	char *s = yytext;
	register unsigned long x, limit;
	register unsigned long i = 0;

	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"PSINTEGER radix->%s\n",yytext));
	    while (*s != '#') {
		base *= 10;
		base += *s++ - '0';
		if (base > 32) break;
	    }

	    if ((base < 2) || (base > 36)) {goto error;}
	    else {
		limit = MAX_ULONG / base;
		s++; /* skip # sign */
		while (*s != '\0') {
		    if (i > limit) goto error;
		    i *= base;
		    if (isdigit(*s)) { x = *s - '0';}
		    else { x = (*s | 040) - ('a'-10);}
		    if (x >= base) goto error;
		    if (x > (MAX_ULONG - i)) goto error;
		    i += x;
		    s++;
		}
	    }
	    yylval.intobj = i;
	    return PSINTEGER;

	    error:;
	    ErrIntro(yylineno);
	    fprintf(stderr,"invalid radix number %s\n",yytext);
	    yylval.intobj = 0; /* ERROR */
	    return PSINTEGER;
	}
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 422 "lexer.l"
{
				/* a float */
	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"PSREAL ->%s\n",yytext));
	    yylval.object = psw_malloc(strlen(yytext) + 1);
	    strcpy(yylval.object,yytext);
	    return PSREAL;
	}
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 433 "lexer.l"
{			/* start PS string */
	if (nonComment) {
	    newLine = false;
	    BEGIN STR;
	    parens=1;
	    sbody = string_temp;
	    curleng = 0;
	    strlineno = yylineno;
	    *sbody = '\0';
	}
}
	YY_BREAK

	/* inside PS strings */

case 37:
YY_RULE_SETUP
#line 449 "lexer.l"
{			/* balancing parens */
	if (yyleng + curleng >= maxstring) {
		stringerr(1);
		BEGIN PS;
		*sbody = '\0';
		return PSSTRING;
	}
	curleng += yyleng;
	parens++;
	*sbody++ = '(';
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 461 "lexer.l"
{			/* balancing parens or end string */
	if ((--parens) == 0) {
		BEGIN PS;
		*sbody = '\0';
		yylval.object = psw_malloc(strlen(string_temp) + 1);
		strcpy(yylval.object, string_temp);
		DEBUGP((stderr,"PSSTRING ->%s\n",string_temp));
		return PSSTRING;
	}
	else if (yyleng + curleng >= maxstring) {
		stringerr(1);
		BEGIN PS;
		*sbody = '\0';
		return PSSTRING;
	}
	curleng += yyleng;
	*sbody++ = ')';
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 480 "lexer.l"
{	/* quoted octal byte */
	register char *c = yytext;

	if (4 + curleng >= maxstring) {
		stringerr(1);
		BEGIN PS;
		*sbody = '\0';
		return PSSTRING;
	}
	curleng += 4;
	sprintf(sbody,"\\%03.3s",(yytext + 1));
	sbody += 4;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 495 "lexer.l"
{ /* ignore quoted newline */
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 498 "lexer.l"
{ /* keep quoted backslashes in */
	if (yyleng + curleng >= maxstring) {
		stringerr(1);
		BEGIN PS;
		*sbody = '\0';
		return PSSTRING;
	}
	*sbody++ = '\\';
	*sbody++ = '\\';
	curleng += 2;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 511 "lexer.l"
{		/* other quoted char, including parens */
	if (yyleng + curleng >= maxstring) {
		stringerr(1);
		BEGIN PS;
		*sbody = '\0';
		return PSSTRING;
	}
	switch (yytext[1]) {
	case 'b':
	    *sbody++ = '\b';
	    break;
	case 'f':
	    *sbody++ = '\f';
	    break;
	case 'n':
	    *sbody++ = '\012';
	    break;
	case 'r':
	    *sbody++ = '\015';
	    break;
	case 't':
	    *sbody++ = '\t';
	    break;
	default:
	    *sbody++ = yytext[1];
	    break;
	}
	curleng++;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 542 "lexer.l"
{		/* newline in a string */
	if (yyleng + curleng >= maxstring) {
		stringerr(1);
		BEGIN PS;
		*sbody = '\0';
		return PSSTRING;
	}
	curleng += yyleng;

	*sbody++ = '\n';
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 554 "lexer.l"
{		/* anything else */
	register int i = yyleng;
	register char *c = yytext;

	if (yyleng + curleng >= maxstring) {
		stringerr(1);
		BEGIN PS;
		*sbody = '\0';
		return PSSTRING;
	}
	curleng += yyleng;
	for (; i > 0; --i) *sbody++ = *c++;
}
	YY_BREAK

	/* hexidecimal strings "< >" */

case 45:
YY_RULE_SETUP
#line 572 "lexer.l"
{			/* begin hex string */
	if (nonComment) {
	    newLine = false;
	    BEGIN HEX;
	    sbody = string_temp;
	    *sbody = '\0';
	    curleng = 0;
	    strlineno = yylineno;
	    hexstringerrs = 0;
	}
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 584 "lexer.l"
{			/* hex whitespace */
	/* ignore */
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 588 "lexer.l"
{		/* hex string data */
	if (yyleng + curleng >= maxstring) {
		stringerr(2);
		*sbody = '\0';
		BEGIN PS;
		return PSHEXSTRING;
	}
	curleng += yyleng;
	strcpy(sbody,yytext);
	sbody += yyleng;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 600 "lexer.l"
{			/* end hex string */
	BEGIN PS;
	*sbody = '\0';
	DEBUGP((stderr,"PSHEXSTRING ->%s\n",string_temp));
	yylval.object = psw_malloc(strlen(string_temp) + 1);
	strcpy(yylval.object, string_temp);
	return PSHEXSTRING;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 609 "lexer.l"
{	/* ERROR */
	if (hexstringerrs == 0) { /* only complain once per string */
	    ErrIntro(yylineno);
	    fprintf(stderr,"invalid characters in hex string '%s'\n",yytext);
	    hexstringerrs++;
	}
}
	YY_BREAK

	/* straight postscript */

case 50:
YY_RULE_SETUP
#line 622 "lexer.l"
{			/* dictionary construct begin */
	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"PSNAME %s\n",yytext));
	    yylval.object = psw_malloc(strlen(yytext) + 1);
	    strcpy(yylval.object, yytext);
	    return PSNAME;
	}
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 632 "lexer.l"
{			/* dictionary construct end */
	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"PSNAME %s\n",yytext));
	    yylval.object = psw_malloc(strlen(yytext) + 1);
	    strcpy(yylval.object, yytext);
	    return PSNAME;
	}
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 642 "lexer.l"
{		/* PS self delimiter */
	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"PS ->%s\n",yytext));
	    return (yytext[0]);
	}
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 650 "lexer.l"
{		/* boolean */
	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"PSBOOLEAN %s\n",yytext));
	    yylval.intobj = (*yytext == 't');
	    return PSBOOLEAN;
	}
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 659 "lexer.l"
{	/* literal name */
	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"PSLITNAME %s\n",yytext));
	    yylval.object = psw_malloc(strlen(yytext));
	    strcpy(yylval.object, yytext+1);
	    return PSLITNAME;
	}
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 669 "lexer.l"
{	/* executable name */
	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"PSNAME %s\n",yytext));
	    yylval.object = psw_malloc(strlen(yytext) + 1);
	    strcpy(yylval.object, yytext);
	    return PSNAME;
	}
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 679 "lexer.l"
{				/* special case */
	if (nonComment) {
	    newLine = false;
	    unput('/');
	    yylval.object = psw_malloc(2);
	    strcpy(yylval.object, "*");
	    return PSNAME;
	}
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 689 "lexer.l"
{	/* \name[index] */
	if (nonComment) {
	    DEBUGP((stderr,"\\PSNAME %s\n",yytext));
	    yylval.object = psw_malloc(strlen(yytext));
	    strcpy(yylval.object, yytext+1);
	    BEGIN SUB;
	    return PSSUBNAME;
	}
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 699 "lexer.l"
{	/* [index] */
	if (nonComment) {
	    int len = strlen(yytext);
	    DEBUGP((stderr,"PSINDEX %s\n",yytext));
	    if (len == 2) {
		ErrIntro(yylineno);
		fprintf(stderr,"parameter index expression empty\n");
		yylval.object = "0";
	    }
	    else {
		yylval.object = psw_malloc(len);
		strncpy(yylval.object, yytext+1, len-2);
		yylval.object[len-2] = '\0';
	    }
	    BEGIN PS;
	    return PSINDEX;
	}
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 718 "lexer.l"
{ /* error */
	if (nonComment) {
	    ErrIntro(yylineno);
	    fprintf(stderr,"parameter index expression error\n");
	    yylval.object = "0";
	    BEGIN PS;
	    return PSINDEX;
	}
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 728 "lexer.l"
{	/* ERROR */
	if (nonComment) {
	    newLine = false;
	    DEBUGP((stderr,"PS JUNK ->%s\n",yytext));
	    ErrIntro(yylineno);
	    fprintf(stderr,"invalid characters '%s'\n",yytext);
	}
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 737 "lexer.l"
{ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 739 "lexer.l"
{
	newLine = true;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 743 "lexer.l"
{		/* passthru stuff */
	ECHO;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 747 "lexer.l"
{
	outlineno++;
#ifdef os_mpw
	SpinCursor(1);
	output('\n');
#else
	ECHO;
#endif
};
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 757 "lexer.l"
{		/* C comments on */
	nonComment = false;
	ECHO;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 762 "lexer.l"
{		/* C comments off */
	if (!nonComment) {
		nonComment = true;
		ECHO;
	}
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 769 "lexer.l"
ECHO;
	YY_BREAK
#line 1953 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(PS):
			case YY_STATE_EOF(STR):
			case YY_STATE_EOF(HEX):
			case YY_STATE_EOF(DEF):
			case YY_STATE_EOF(SUB):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 308 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 308 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 307);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 769 "lexer.l"


int yywrap () {
    if (!feof(yyin))
    	return (0);
    /* The shipped pswrap says nothing when the input runs out, whether or
       not a definition was still open; the parser reports the syntax
       error that follows. */
    return (1);
}

void stringerr(type)
	int type;
{
    extern char *currentPSWName;
    extern char *ifile;

    ErrIntro(strlineno);
    fprintf(stderr,"%sstring too long (caught at line %d)\n",
    	((type==1)?"":"hex "),yylineno);
    errorCount++;
    return;
}
