#
# PPCAwacs driver relocatable Makefile
#

NAME = PPCAwacs_reloc

PRODUCT = PPCAwacs_reloc

HFILES = PPCAwacsDriver.h awacs.h

MFILES = PPCAwacsDriver.m awacs.m

OTHERSRCS = Makefile Makefile.preamble Makefile.postamble

MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = tool.make

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
