#
# Makefile.preamble for PPCAwacs driver
#

# Additional flags
OTHER_CFLAGS = -Wall -Wno-import
OTHER_MFLAGS = -Wall -Wno-import

# Include paths
INCLUDEPATHS = -I$(NEXT_ROOT)/System/Library/Frameworks/System.framework/PrivateHeaders

# Optimization
OPTIMIZATION_CFLAG = -O2
