##
# Makefile for SerialPointingDevice driver
##

NAME = SerialPointingDevice
BUNDLE_EXTENSION = config

OBJC_FILES = SerialPointingDevice.m
HEADER_FILES = SerialPointingDevice.h SerialMouseProtocols.h SerialPointingDeviceTypes.h

OTHER_RESOURCES = SerialPointingDevice.table
INSTALL_BIN_DIR = /System/Library/Drivers

MAKEFILEDIR = $(NEXT_ROOT)/NextDeveloper/Makefiles/app
MAKEFILE = bundle.make

include $(MAKEFILEDIR)/$(MAKEFILE)
