NAME = ES1x88AudioDriver_reloc

CFILES = ES1x88AudioDriver.m ES1x88AudioDriverKernelServerInstance.m

HFILES = ES1x88AudioDriver.h ES1x88AudioDriverKernelServerInstance.h

MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = tool.make

LIBS = -lDriver

OTHER_CFLAGS = -DDRIVER_PRIVATE

-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
