###############################################################################
#  NeXT Makefile.postamble
###############################################################################

# driver.make movehelp always mv's English.lproj/DriverHelp; Floppy has Help/.
movehelp:
	@true
