###############################################################################
#  NeXT Makefile.postamble
#  Copyright 1998, NeXT Software, Inc.
#
#  This Makefile is used for configuring the standard app makefiles associated
#  with ProjectBuilder.
#
#  Use this file to add additional rules or override default behavior.
#
###############################################################################
