###############################################################################
#  NeXT Makefile.preamble
###############################################################################

OTHER_CFLAGS = -g -Wall
OTHER_LDFLAGS =
OTHER_LIBS =
LIBS =
FRAMEWORKS =

MFILES = Adaptec2940.m Adaptec2940Thread.m Adaptec2940Routines.m

HFILES = Adaptec2940.h Adaptec2940Private.h Adaptec2940Types.h

