NAME = Intel82596NetworkDriver
PROJECTVERSION = 1.0
PROJECT_TYPE = Driver
LANGUAGE = English
LOCAL_RESOURCES = Localizable.strings DriverHelp
GLOBAL_RESOURCES = Default.table
CLASSES =
HFILES =
TOOLS = Intel82596NetworkDriver.lksproj
OTHERSRCS = Makefile Makefile.preamble DriverInfo
MAKEFILEDIR = $(MAKEFILEPATH)/pb_makefiles
CODE_GEN_STYLE = DYNAMIC
MAKEFILE = driver.make
NEXTSTEP_INSTALLDIR = $(NEXT_ROOT)/private/Drivers
BUNDLE_EXTENSION = config
include $(MAKEFILEDIR)/platform.make
-include Makefile.preamble
include $(MAKEFILEDIR)/$(MAKEFILE)
-include Makefile.postamble
-include Makefile.dependencies
