HOST_CC ?= cc
HOST_CFLAGS ?= -std=c89 -pedantic -Wall -Wextra -Werror
HOST_CPPFLAGS ?= -D__ppc__

mpic_direct_test: mpic_direct_test.c ../powermac/chips/mpic.c
	$(HOST_CC) $(HOST_CFLAGS) -DMPIC_DIRECT_HOST_TEST \
	    -I../powermac -o $@ mpic_direct_test.c ../powermac/chips/mpic.c

pe_keylargo_test: pe_keylargo_test.c ../powermac/chips/keylargo_audio.c
	$(HOST_CC) $(HOST_CFLAGS) \
	    -Wno-import-preprocessor-directive-pedantic $(HOST_CPPFLAGS) \
	    -I../../../../kernel-7 \
	    -o $@ pe_keylargo_test.c ../powermac/chips/keylargo_audio.c

interrupt_depth_test: interrupt_depth_test.c
	$(HOST_CC) $(HOST_CFLAGS) -o $@ interrupt_depth_test.c

keylargo_discovery_test: keylargo_discovery_test.c
	$(HOST_CC) $(HOST_CFLAGS) -o $@ keylargo_discovery_test.c

macrisc_discovery_test: macrisc_discovery_test.c \
    ../powermac/macrisc_discovery.c ../powermac/macrisc_discovery.h
	$(HOST_CC) $(HOST_CFLAGS) -DMACRISC_HOST_TEST -I../powermac \
	    -o $@ macrisc_discovery_test.c ../powermac/macrisc_discovery.c

macrisc_platform_test: macrisc_platform_test.c \
    ../powermac/macrisc_discovery.c ../powermac/macrisc_discovery.h \
    ../powermac/macrisc_dt.c ../powermac/macrisc_dt.h \
    ../powermac/families/macrisc.c ../powermac/families/macrisc.h \
    ../powermac/chips/mpic.c ../powermac/interrupts.h
	$(HOST_CC) $(HOST_CFLAGS) -DMACRISC_HOST_TEST -DMPIC_DIRECT_HOST_TEST \
	    -I../powermac -I../../../../kernel-7 \
	    -o $@ macrisc_platform_test.c ../powermac/macrisc_discovery.c \
	    ../powermac/macrisc_dt.c ../powermac/families/macrisc.c \
	    ../powermac/chips/mpic.c

test: mpic_direct_test pe_keylargo_test interrupt_depth_test \
    keylargo_discovery_test macrisc_discovery_test macrisc_platform_test
	./mpic_direct_test
	./pe_keylargo_test
	./interrupt_depth_test
	./keylargo_discovery_test
	./macrisc_discovery_test
	./macrisc_platform_test

clean:
	rm -f mpic_direct_test pe_keylargo_test interrupt_depth_test \
	    keylargo_discovery_test macrisc_discovery_test macrisc_platform_test
