###############################################################################
#  NeXT Makefile.preamble
###############################################################################

OTHER_CFLAGS = -g -Wall
OTHER_LDFLAGS =
OTHER_LIBS =
LIBS =
FRAMEWORKS =

MFILES = BusLogicFPSCSI.m
CFILES = FlashPoint.c

HFILES = BusLogicFPSCSI.h FlashPoint.h

