###############################################################################
#  NeXT Makefile.preamble
###############################################################################

OTHER_CFLAGS = -g -Wall -Wno-format
OTHER_LDFLAGS =
OTHER_LIBS =
LIBS =
FRAMEWORKS =

CLASSES += SCSIBus.m
HFILES += SCSIBus.h
