##
# Makefile for ATIMach64 Display Driver
##

NAME = ATIMach64DisplayDriver
BUNDLE_EXTENSION = config

OBJC_FILES = ATIMach64DisplayDriver.m ATIMach64DisplayDriverKernelServerInstance.m
HEADER_FILES = ATIMach64DisplayDriver.h ATIMach64DisplayDriverKernelServerInstance.h ATIMach64Regs.h

OTHER_RESOURCES = Default.table
INSTALL_BIN_DIR = /System/Library/Drivers

MAKEFILEDIR = $(NEXT_ROOT)/NextDeveloper/Makefiles/app
MAKEFILE = bundle.make

include $(MAKEFILEDIR)/$(MAKEFILE)
